### ISSUE TITLE
Why are my alacritty vim colors different than iterm2?

### ISSUE THREAD

**Issue by abbood** [morhetz/gruvbox#447]
I’ve swithced from iterm2 to alacritty. However I noticed that although I’m using the same vim color scheme ([gruvbox][1]), they colors appear different (especially the dark gray), notice the difference:

**Iterm2**
![Screenshot 2023-05-27 at 8 17 07 AM](https://github.com/morhetz/gruvbox/assets/774379/4d4b6def-4da9-473a-aeaa-fab92b72e31d)

**Alacritty**

![Screenshot 2023-05-27 at 8 16 20 AM](https://github.com/morhetz/gruvbox/assets/774379/fd2928a9-5be5-4fc7-8dca-fa6c71c80151)

(notice how the comment for example in alacritty is more purplish)

Here is my iTerm2 [color config][4], and here is my alacritty color config:

```
window:
  padding:
    x: 10
    y: 10

key_bindings:
  - { key: Return,   mods: Command,         action: ToggleSimpleFullscreen }

import:
 - ~/.config/alacritty/themes/themes/base16_default_dark.yaml

font:
  normal:
    family: HackNerdFontCompleteNerdFont Nerd Font 
    style:  Regular
  bold:
    family: Hack Nerd Font 
    style:  Bold
  italic:
    family: Hack Nerd Font 
    style:  Italic
  bold_italic:
    family: Hack Nerd Font 
    style: Bold Italic
  size: 14

selection:
  save_to_clipboard: true

draw_bold_text_with_bright_colors: true
```
were I imported the color theme from [here][5].

  [1]: https://github.com/morhetz/gruvbox
  [2]: https://i.stack.imgur.com/OXSIN.png
  [3]: https://i.stack.imgur.com/xIHbx.png
  [4]: https://gist.github.com/abbood/0a1ebbd439a92a5dc230b58ea82f583e
  [5]: https://github.com/alacritty/alacritty-theme
